### ISSUE TITLE
Allow Users to Update In-Game Date 

### ISSUE THREAD

**Issue by Evitcani** [Evitcani/party-management-api#2]
This feature will allow the user to change the in-game date for a party. 

The endpoint should resemble the following:
```yaml
/api/v1/currentDates?partyId=[PARTY ID]
  post:
    description: "Creates a new current date if none exists for the given party. Otherwise, updates."
/api/v1/currentDates/:id
  put:
    description: "Updates a date."
```
**API Work**
- [ ] POST endpoint to create a new date for a given party
- [ ] PUT endpoint to update existing endpoint
- [ ] Document endpoints fully
- [ ] Cleanup code

**Bot Work**
- [ ] Make command `$date [#]` and `$date [#] days` advance the current date by `[#]` days
- [ ] Make command `$date ~set [day]/[month]/[year]` set the date to the given time.
- [ ] Make command `$date ~party [Party Name] ~calendar [Calendar name]` set a party's default calendar to `[Calendar name]`
